## This code copies and combines various parts of mt other code to get a dataframe that the theory team can use to get their Mathematica results

The code had to be written like this because the node went bad and prevented me from getting specific feateures of data from certain tim

In [1]:
#read in data
import numpy as np
import matplotlib as mpl
import csv
import matplotlib.pyplot as plt
import pandas as pd
from pre_and_post_valuations_data import transaction_data_file, block_data_file, pre_geth_file, \
    geth_reccomendation_file, suite_spot_txn, suite_spot_blx, post_eip_oct_txn_file, \
    october_block_data



#Read in the data, use your own machines specific path as you see fit
transaction_data_d1=pd.read_csv(transaction_data_file)
block_data_d1=pd.read_csv(block_data_file)
pre_geth=pd.read_csv(pre_geth_file)
geth_r=pd.read_csv(geth_reccomendation_file)
suite_txn=pd.read_csv(suite_spot_txn)
suite_blx=pd.read_csv(suite_spot_blx)
post_eip_oct_txn=pd.read_csv(post_eip_oct_txn_file)
post_eip_oct_blx=pd.read_csv(october_block_data)

def random_index_generator(my_list,num_of_indexes):
    my_max=len(my_list)-1
    result=np.random.uniform(0,my_max,num_of_indexes)
    index=[round(x) for x in result]
    return [my_list[x] for x in index]

def outlier_trimmer(p_up,p_lo,my_list):
    my_up=np.percentile(my_list,p_up)
    my_lo=np.percentile(my_list,p_lo)
    return [x for x in my_list if (x < my_up)&(x > my_lo)]

In [2]:
post_eip_oct_txn=\
post_eip_oct_txn[pd.notnull(post_eip_oct_txn.max_priority_fee_per_gas)]


max_block=np.max(post_eip_oct_txn.block_number)
min_block=np.min(post_eip_oct_txn.block_number)

display(post_eip_oct_txn)
display(post_eip_oct_blx)



print(max_block,min_block)



post_eip_oct_blx=post_eip_oct_blx[post_eip_oct_blx.number < max_block ]
post_eip_oct_blx=post_eip_oct_blx[post_eip_oct_blx.number > min_block ]

display(post_eip_oct_blx)

,hash,nonce,block_hash,block_number,transaction_index,from_address,to_address,value,gas,gas_price,input,block_timestamp,max_fee_per_gas,max_priority_fee_per_gas,transaction_type
4,0x11e5a4d21139c7a0de556f791ebc0f10c273cec96efc...,270208,0x12b63c589dcd362d45c65b58d6a6fa72226d60832b00...,13360100,4,0x5ab9d116a53ef41063e3eae26a7ebe736720e9ba,0x7a250d5630b4cf539739df2c5dacb4c659f2488d,0,250000,185000000000,0x38ed1739000000000000000000000000000000000000...,1633451105,1.850000e+11,7.000000e+10,2
5,0xaeefeffd8eab02be8ffa5b1e3f8acf83855ac4a3567f...,55,0x12b63c589dcd362d45c65b58d6a6fa72226d60832b00...,13360100,5,0x204a731a626438a0b2a657378668cfbfe70a90f5,0x96f47d56f25d2ba629db1f55db0517dee67640e1,0,119876,181726253573,0x6a76120200000000000000000000000001fdc62ff435...,1633451105,1.817263e+11,7.733000e+10,2
6,0x568fd3a753000ce8b00651daaff922533afc06e7e355...,2760623,0x12b63c589dcd362d45c65b58d6a6fa72226d60832b00...,13360100,6,0xb5d85cbf7cb3ee0d56b3bb207d5fc4b82f43f511,0x1e852c5bbe4c7cda0ccac3c4561db6cc9bc39eb9,59104921050000000000,21000,162831880856,0x,1633451105,2.820000e+11,4.000000e+09,2
7,0x06190ba28039040ac4d79daff31a32f958937414d474...,3042959,0x12b63c589dcd362d45c65b58d6a6fa72226d60832b00...,13360100,7,0x3cd751e6b0078be393132286c442345e5dc49699,0xac4c7b2c36f4beed0963eef8215b2fa9bc9be15d,29210120000000000,21000,162831880856,0x,1633451105,2.820000e+11,4.000000e+09,2
8,0x07796eaca8cbf3b748305cf26214c99ffe5d043157a2...,3042960,0x12b63c589dcd362d45c65b58d6a6fa72226d60832b00...,13360100,8,0x3cd751e6b0078be393132286c442345e5dc49699,0xdac17f958d2ee523a2206206994597c13d831ec7,0,250000,162831880856,0xa9059cbb000000000000000000000000ae31986171da...,1633451105,2.820000e+11,4.000000e+09,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
965764,0x0762560fa72fdb7b92a905b260581b017a8c9ce22d11...,113,0xa8146ae6525c1090e1d15931cc5dcb461d1e8b8c0d27...,13364999,262,0x41c8730c4a8a07d523e25f80c9b477337e16fa9c,0xa4dc59bae0ca1a0e52dac1885199a2fb53b3abe3,0,45000,100976098829,0x3e12170f000000000000000000000000d8aa5ed74e5a...,1633518046,1.089530e+11,1.410000e+09,2
965766,0x027bab6777af58610e94f4a5d8bafae9d923646bda11...,425,0xa8146ae6525c1090e1d15931cc5dcb461d1e8b8c0d27...,13364999,264,0x26b3eea1cd34a4aff7ce828a5f71daac042d38e0,0x6ad567e7d23787cbc025f168a102fb394e5a85b0,271499366019297752,21000,100712231644,0x,1633518046,1.915743e+11,1.146133e+09,2
965769,0xfb608435b14860a8a7cc52f648d58bd32d58515f376b...,484,0xa8146ae6525c1090e1d15931cc5dcb461d1e8b8c0d27...,13364999,267,0x88004a0f6e7dfc2ef21c49b614eb0a3569e29525,0x9757f2d2b135150bbeb65308d4a91804107cd8d6,287000000000000000,327208,100654122220,0xe99a3f80000000000000000000000000000000000000...,1633518046,1.006541e+11,1.006541e+11,2
965770,0xa6e0986b89ca14e87572ca5ae467473221e2ed4a04d2...,312,0xa8146ae6525c1090e1d15931cc5dcb461d1e8b8c0d27...,13364999,268,0x88aa631b427cf96d12d91885e7026a3636d90070,0x9757f2d2b135150bbeb65308d4a91804107cd8d6,789250000000000000,327208,100654122220,0xe99a3f80000000000000000000000000000000000000...,1633518046,1.006541e+11,1.006541e+11,2
965771,0x8842a2c108d0ea89794ce24bdbe92022c03a76162331...,1091,0xa8146ae6525c1090e1d15931cc5dcb461d1e8b8c0d27...,13364999,269,0x9af999595a08210fcaa705f0491a800551f73388,0x3d9819210a31b4961b30ef54be2aed79b9c9cd3b,0,351217,100566098829,0x1c3db2e00000000000000000000000009af999595a08...,1633518046,2.010862e+11,1.000000e+09,2

,number,gas_limit,gas_used,timestamp,transaction_count,base_fee_per_gas
0,13340130,30117238,12291790,1633181352,128,46881572638
1,13340131,30146648,29989476,1633181363,293,45804836329
2,13340132,30117209,7144499,1633181391,66,51470739060
3,13340133,30087799,30071371,1633181395,383,48089409412
4,13340134,30117180,17511459,1633181436,142,54094021758
...,...,...,...,...,...,...
169976,13509925,30056703,27504936,1635480560,663,144885233991
169977,13509926,30027352,4148809,1635480571,63,159920756992
169978,13509927,30056674,13838680,1635480573,226,145454631614
169979,13509928,30086025,4845441,1635480584,80,144015341287
169980,13509929,30056646,30044345,1635480587,510,131811945220

13365000 13360000

,number,gas_limit,gas_used,timestamp,transaction_count,base_fee_per_gas
19900,13360130,29999944,26093891,1633451493,337,134162209076
19901,13360131,30000000,4127777,1633451508,54,146565437898
19902,13360132,30029295,7522143,1633451509,98,133286336858
19903,13360133,30058619,23324929,1633451514,341,124972385055
19904,13360134,30087972,2292007,1633451533,31,133594899045
...,...,...,...,...,...,...
25095,13364925,30029238,29667248,1633517122,399,117700237823
25096,13364926,30000000,7243497,1633517155,96,132058060672
25097,13364927,30029295,1875831,1633517165,23,123522154474
25098,13364928,30000000,6941025,1633517168,109,110010890610
25099,13364929,30000000,23950120,1633517179,229,102622765468

In [3]:

my_blocks=list(post_eip_oct_blx.number)

avg_gas_price=[]


for i in my_blocks:
    current_itteration=post_eip_oct_txn[post_eip_oct_txn.block_number == i]
    avg_gas_price.append(np.mean(current_itteration.gas_price))
    
post_eip_oct_blx['avg_gas_price']=avg_gas_price
display(post_eip_oct_blx)

,number,gas_limit,gas_used,timestamp,transaction_count,base_fee_per_gas,avg_gas_price
19900,13360130,29999944,26093891,1633451493,337,134162209076,1.377075e+11
19901,13360131,30000000,4127777,1633451508,54,146565437898,1.514650e+11
19902,13360132,30029295,7522143,1633451509,98,133286336858,1.370622e+11
19903,13360133,30058619,23324929,1633451514,341,124972385055,1.291899e+11
19904,13360134,30087972,2292007,1633451533,31,133594899045,1.353449e+11
...,...,...,...,...,...,...,...
25095,13364925,30029238,29667248,1633517122,399,117700237823,1.259941e+11
25096,13364926,30000000,7243497,1633517155,96,132058060672,1.368194e+11
25097,13364927,30029295,1875831,1633517165,23,123522154474,1.263407e+11
25098,13364928,30000000,6941025,1633517168,109,110010890610,1.205361e+11
25099,13364929,30000000,23950120,1633517179,229,102622765468,1.072199e+11

In [4]:

#######################################################################################################################
## ADDING THE GAS LIMITS AND BASE FEE INTO THE DATAFRAME
#######################################################################################################################
## first we put the gas limits as well as the base fee into the  transaction dataframe
#######################################################################################################################


#######################################################################################################################
## ADDING THE GAS LIMITS AND BASE FEE INTO THE DATAFRAME
#######################################################################################################################
## first we put the gas limits as well as the base fee into the  transaction dataframe
#######################################################################################################################





#Get the block number and gas limits and base fee from the dataset
my_block_number=list(block_data_d1.block_number)
my_gas_limit=list(block_data_d1.gas_limit)
my_base_fee=list(block_data_d1.base_fee_per_gas)
#initialize a dictionary to assign gas limits and base fee to the transaction data
gas_limit_tracker={}
base_fee_tracker={}


#makes a dicionary with the key being the block number and the 
#value being the gas limits and base fee, because this will allow us to 
#easily assign a gas limit and base fee to the transaction going forward
for i in range(len(my_block_number)):
    gas_limit_tracker[my_block_number[i]]=my_gas_limit[i]
    base_fee_tracker[my_block_number[i]]=my_base_fee[i]
    
    
##get the block numbers from the transaction data
transaction_block_numbers=list(transaction_data_d1.block_number)


#initialize a list for the purpose of saving the gas limits that will 
#be assigned to the transaction data and assign the correct information
gas_limits_for_transaction_data_d1=[gas_limit_tracker[x] for x in transaction_block_numbers]
base_fee_for_transaction_data_d1=[base_fee_tracker[x] for x in transaction_block_numbers]

    
#add the column into the dataframe
#transaction_data['gas_limit']=gas_limits_for_transaction_data
transaction_data_d1['base_fee']=base_fee_for_transaction_data_d1


# The final step is to remove the NA's from then dataframe, from testing of the 
# dataset, i have found that the max priority fee per gas and the max fee per gas
# have the the same number of NA's -this can be oberved with the line 
# np.sum(transaction_data.isna())- that we can remove the NA's with the line...
transaction_data_d1=transaction_data_d1[pd.notnull(transaction_data_d1.max_fee_per_gas)]

In [5]:
#day one valuations
#grab the block numbers from the dataset
my_blocks=list(set(list(transaction_data_d1.block_number)))


#grab the usable block numbers, as we cant derive reccomendations from the 
#first 100 blocks because the reccomendation is based on the previous 100 
#blocks
usable_blocks=my_blocks[101:]
#get the first block
usable_blocks[0]




#initialize a list to contain the minimum
min_list=[]

#this loop goes through each of the 
#usable blocks, finds the lowest rescaled gas price, 
#then gets the bid associated with that
#gas price, and then adds it to the min_list
for i in my_blocks:        
    current_itteration=transaction_data_d1[transaction_data_d1.block_number == i]
    tip_values=list(current_itteration.max_priority_fee_per_gas)
    min_value=np.min(tip_values)
    min_list.append(min_value)
    
        
        
        
#initialize a list to contain the geth reccomendations
geth_reccomendation=[]


for i in range(len(usable_blocks)):
    geth_reccomendation.append(np.percentile(min_list[i:i+100],60))

    
#use only the usable blocks for our final dataframe  
final_dataframe_d1=transaction_data_d1[transaction_data_d1.block_number >= usable_blocks[0]]


#initialize a dictionary to contain the geth reccomendations
geth_r_tracker={}

#assign the values based on the block number
for i in range(len(usable_blocks)):
    geth_r_tracker[usable_blocks[i]]=geth_reccomendation[i]
    
    
#get the blocks from the dataframe
my_final_blocks=list(final_dataframe_d1.block_number)

#initialize a list that will contain the geth reccomendation
geth_r_for_dataframe=[]

#assign the ressomendation
for i in my_final_blocks:
    geth_r_for_dataframe.append(geth_r_tracker[i])
    
#put the reccomendation back into the dataframe
final_dataframe_d1['geth_recommendation_tip']=geth_r_for_dataframe


#calculate the valuations according to the methodology of the 
#last paper
final_dataframe_d1['valuations_tip']=final_dataframe_d1['max_priority_fee_per_gas']  \
/ final_dataframe_d1['geth_recommendation_tip']

final_dataframe_d1['geth_recommendation_max_fee']= \
final_dataframe_d1['geth_recommendation_tip'] + \
2 * final_dataframe_d1['base_fee']

final_dataframe_d1['valuations_max_fee']=final_dataframe_d1['max_fee_per_gas'] \
/ final_dataframe_d1['geth_recommendation_max_fee']


#display the results to the user
display(final_dataframe_d1)

/var/folders/l8/p0_hwx4d2hvbqs4crpsfjlzc0000gn/T/ipykernel_6992/2721249139.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_dataframe_d1['geth_recommendation_tip']=geth_r_for_dataframe
/var/folders/l8/p0_hwx4d2hvbqs4crpsfjlzc0000gn/T/ipykernel_6992/2721249139.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_dataframe_d1['valuations_tip']=final_dataframe_d1['max_priority_fee_per_gas']  \
/var/folders/l8/p0_hwx4d2hvbqs4crpsfjlzc0000gn/T/ipykernel_6992/2721249139.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_dataframe_d1['geth_recommendation_max_fee']= \
/var/folders/l8/p0_hwx4d2hvbqs4crpsfjlzc0000gn/T/ipykernel_6992/2721249139.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_dataframe_d1['valuations_max_fee']=final_dataframe_d1['max_fee_per_gas'] \

,hash,block_number,value,gas,gas_price,max_fee_per_gas,max_priority_fee_per_gas,transaction_type,gas_used,base_fee,geth_recommendation_tip,valuations_tip,geth_recommendation_max_fee,valuations_max_fee
516516,0x4ecc6a513ce1c02e1367c7bca169233d7da61a721d54...,12968054,0.000000e+00,120000,40658350000,4.065835e+10,4.065835e+10,2,43713,34209998215,4.011818e+09,10.134645,7.243181e+10,0.561333
516524,0x9128b87ba28e3bdbb40491ea5d3ec4fffd9bdf24638e...,12968054,0.000000e+00,250000,39209998215,7.200000e+10,5.000000e+09,2,57206,34209998215,4.011818e+09,1.246318,7.243181e+10,0.994038
516787,0x49d63c1b486c0f99c05a5ab4970919684fb23b056c12...,12968055,5.000000e+16,211131,40107493816,4.010749e+10,4.010749e+10,2,201299,32526865584,4.011818e+09,9.997337,6.906555e+10,0.580716
516859,0x865c8eedc70ff15750ced3ed0d714bf8eb440ddd9e33...,12968055,7.075910e+15,21000,36526865584,7.800000e+10,4.000000e+09,2,21000,32526865584,4.011818e+09,0.997054,6.906555e+10,1.129362
516903,0x27d26ab8a6a69e82e4b50e899622e7d193bdb097119c...,12968055,0.000000e+00,362127,35050243944,3.505024e+10,3.505024e+10,2,212973,32526865584,4.011818e+09,8.736749,6.906555e+10,0.507492
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
883769,0xec1a176e7a2cc37389bf2ff27a169a240f1734c33a08...,12969997,2.804744e+16,3000000,29635881520,2.963588e+10,0.000000e+00,2,121233,29635881520,4.000000e+09,0.000000,6.327176e+10,0.468390
883770,0x31eca90accfcb17e2d85dfc6418d420988067bf856e6...,12969997,0.000000e+00,1000000,34505402509,3.450540e+10,3.450540e+10,2,210545,29635881520,4.000000e+09,8.626351,6.327176e+10,0.545352
883837,0xfa623209d41ba4409537b5739d4fa0abbefd687313c2...,12969997,4.109970e+15,42000,31502952651,3.150295e+10,1.867071e+09,2,21000,29635881520,4.000000e+09,0.466768,6.327176e+10,0.497899
883853,0xeb54da76c9059da24af786d1dc97f76da7faebbc9e97...,12969998,0.000000e+00,1000000,165487905007,1.654879e+11,1.654879e+11,2,122846,28080959215,4.000000e+09,41.371976,6.016192e+10,2.750709
883988,0x81d0f73ca88a5d1163e2a73ca97da044facad0dfb963...,12969998,1.497000e+18,21000,35409931432,6.660074e+10,7.328972e+09,2,21000,28080959215,4.000000e+09,1.832243,6.016192e+10,1.107025

In [6]:
##October valuations



post_eip_oct_txn=post_eip_oct_txn[pd.notnull(post_eip_oct_txn.max_priority_fee_per_gas)]
display(post_eip_oct_txn)







#grab the block numbers from the dataset
my_blocks=list(set(list(post_eip_oct_txn.block_number)))


#grab the usable block numbers, as we cant derive reccomendations from the 
#first 100 blocks because the reccomendation is based on the previous 100 
#blocks
usable_blocks=my_blocks[101:]
#get the first block
usable_blocks[0]




#initialize a list to contain the minimum
min_list=[]

#this loop goes through each of the 
#usable blocks, finds the lowest rescaled gas price, 
#then gets the bid associated with that
#gas price, and then adds it to the min_list
for i in my_blocks:        
    current_itteration=post_eip_oct_txn[post_eip_oct_txn.block_number == i]
    tip_values=list(current_itteration.max_priority_fee_per_gas)
    min_value=np.min(tip_values)
    min_list.append(min_value)
    
        
        
        
#initialize a list to contain the geth reccomendations
geth_reccomendation=[]



for i in range(len(usable_blocks)):
    geth_reccomendation.append(np.percentile(min_list[i:i+100],60))



    
#use only the usable blocks for our final dataframe  
final_dataframe_oct=post_eip_oct_txn[post_eip_oct_txn.block_number >= usable_blocks[0]]

#base_fee=list(post_eip_oct_blx.base_fee)

#initialize a dictionary to contain the geth reccomendations
geth_r_tracker={}
#base_fee_tracker={}

#assign the values based on the block number
for i in range(len(usable_blocks)):
    geth_r_tracker[usable_blocks[i]]=geth_reccomendation[i]
#    base_fee_tracker[usable_blocks[i]]=base_fee[i]

    
    
#get the blocks from the dataframe
my_final_blocks=list(final_dataframe_oct.block_number)

#initialize a list that will contain the geth reccomendation
geth_r_for_dataframe=[]
#b_fee_for_dataframe=[]

#assign the ressomendation
for i in my_final_blocks:
    geth_r_for_dataframe.append(geth_r_tracker[i])
#    b_fee_for_dataframe.append(base_fee_tracker[i])
    
#put the reccomendation and base fee back into the dataframe
final_dataframe_oct['geth_recommendation_tip']=geth_r_for_dataframe
#final_dataframe_oct['base_fee']=b_fee_for_dataframe
final_dataframe_oct['geth_recommendation_tip_plus']= \
final_dataframe_oct['geth_recommendation_tip']+1

final_dataframe_oct['max_priority_fee_per_gas_plus']=\
final_dataframe_oct['max_priority_fee_per_gas']+1


#final_dataframe_oct['max_fee_reccomendation']=final_dataframe_oct[\
#'geth_reccomendation_tip_plus']+(2*final_dataframe_oct[''])



final_dataframe_oct['tip_valuations']=final_dataframe_oct['max_priority_fee_per_gas_plus'] \
/final_dataframe_oct['geth_recommendation_tip_plus']

final_dataframe_oct=final_dataframe_oct[pd.notnull(final_dataframe_oct.tip_valuations)]

display(final_dataframe_oct)

,hash,nonce,block_hash,block_number,transaction_index,from_address,to_address,value,gas,gas_price,input,block_timestamp,max_fee_per_gas,max_priority_fee_per_gas,transaction_type
4,0x11e5a4d21139c7a0de556f791ebc0f10c273cec96efc...,270208,0x12b63c589dcd362d45c65b58d6a6fa72226d60832b00...,13360100,4,0x5ab9d116a53ef41063e3eae26a7ebe736720e9ba,0x7a250d5630b4cf539739df2c5dacb4c659f2488d,0,250000,185000000000,0x38ed1739000000000000000000000000000000000000...,1633451105,1.850000e+11,7.000000e+10,2
5,0xaeefeffd8eab02be8ffa5b1e3f8acf83855ac4a3567f...,55,0x12b63c589dcd362d45c65b58d6a6fa72226d60832b00...,13360100,5,0x204a731a626438a0b2a657378668cfbfe70a90f5,0x96f47d56f25d2ba629db1f55db0517dee67640e1,0,119876,181726253573,0x6a76120200000000000000000000000001fdc62ff435...,1633451105,1.817263e+11,7.733000e+10,2
6,0x568fd3a753000ce8b00651daaff922533afc06e7e355...,2760623,0x12b63c589dcd362d45c65b58d6a6fa72226d60832b00...,13360100,6,0xb5d85cbf7cb3ee0d56b3bb207d5fc4b82f43f511,0x1e852c5bbe4c7cda0ccac3c4561db6cc9bc39eb9,59104921050000000000,21000,162831880856,0x,1633451105,2.820000e+11,4.000000e+09,2
7,0x06190ba28039040ac4d79daff31a32f958937414d474...,3042959,0x12b63c589dcd362d45c65b58d6a6fa72226d60832b00...,13360100,7,0x3cd751e6b0078be393132286c442345e5dc49699,0xac4c7b2c36f4beed0963eef8215b2fa9bc9be15d,29210120000000000,21000,162831880856,0x,1633451105,2.820000e+11,4.000000e+09,2
8,0x07796eaca8cbf3b748305cf26214c99ffe5d043157a2...,3042960,0x12b63c589dcd362d45c65b58d6a6fa72226d60832b00...,13360100,8,0x3cd751e6b0078be393132286c442345e5dc49699,0xdac17f958d2ee523a2206206994597c13d831ec7,0,250000,162831880856,0xa9059cbb000000000000000000000000ae31986171da...,1633451105,2.820000e+11,4.000000e+09,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
965764,0x0762560fa72fdb7b92a905b260581b017a8c9ce22d11...,113,0xa8146ae6525c1090e1d15931cc5dcb461d1e8b8c0d27...,13364999,262,0x41c8730c4a8a07d523e25f80c9b477337e16fa9c,0xa4dc59bae0ca1a0e52dac1885199a2fb53b3abe3,0,45000,100976098829,0x3e12170f000000000000000000000000d8aa5ed74e5a...,1633518046,1.089530e+11,1.410000e+09,2
965766,0x027bab6777af58610e94f4a5d8bafae9d923646bda11...,425,0xa8146ae6525c1090e1d15931cc5dcb461d1e8b8c0d27...,13364999,264,0x26b3eea1cd34a4aff7ce828a5f71daac042d38e0,0x6ad567e7d23787cbc025f168a102fb394e5a85b0,271499366019297752,21000,100712231644,0x,1633518046,1.915743e+11,1.146133e+09,2
965769,0xfb608435b14860a8a7cc52f648d58bd32d58515f376b...,484,0xa8146ae6525c1090e1d15931cc5dcb461d1e8b8c0d27...,13364999,267,0x88004a0f6e7dfc2ef21c49b614eb0a3569e29525,0x9757f2d2b135150bbeb65308d4a91804107cd8d6,287000000000000000,327208,100654122220,0xe99a3f80000000000000000000000000000000000000...,1633518046,1.006541e+11,1.006541e+11,2
965770,0xa6e0986b89ca14e87572ca5ae467473221e2ed4a04d2...,312,0xa8146ae6525c1090e1d15931cc5dcb461d1e8b8c0d27...,13364999,268,0x88aa631b427cf96d12d91885e7026a3636d90070,0x9757f2d2b135150bbeb65308d4a91804107cd8d6,789250000000000000,327208,100654122220,0xe99a3f80000000000000000000000000000000000000...,1633518046,1.006541e+11,1.006541e+11,2
965771,0x8842a2c108d0ea89794ce24bdbe92022c03a76162331...,1091,0xa8146ae6525c1090e1d15931cc5dcb461d1e8b8c0d27...,13364999,269,0x9af999595a08210fcaa705f0491a800551f73388,0x3d9819210a31b4961b30ef54be2aed79b9c9cd3b,0,351217,100566098829,0x1c3db2e00000000000000000000000009af999595a08...,1633518046,2.010862e+11,1.000000e+09,2

/var/folders/l8/p0_hwx4d2hvbqs4crpsfjlzc0000gn/T/ipykernel_6992/332012410.py:84: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_dataframe_oct['geth_recommendation_tip']=geth_r_for_dataframe
/var/folders/l8/p0_hwx4d2hvbqs4crpsfjlzc0000gn/T/ipykernel_6992/332012410.py:86: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_dataframe_oct['geth_recommendation_tip_plus']= \
/var/folders/l8/p0_hwx4d2hvbqs4crpsfjlzc0000gn/T/ipykernel_6992/332012410.py:89: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_dataframe_oct['max_priority_fee_per_gas_plus']=\
/var/folders/l8/p0_hwx4d2hvbqs4crpsfjlzc0000gn/T/ipykernel_6992/332012410.py:98: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_dataframe_oct['tip_valuations']=final_dataframe_oct['max_priority_fee_per_gas_plus'] \

,hash,nonce,block_hash,block_number,transaction_index,from_address,to_address,value,gas,gas_price,input,block_timestamp,max_fee_per_gas,max_priority_fee_per_gas,transaction_type,geth_recommendation_tip,geth_recommendation_tip_plus,max_priority_fee_per_gas_plus,tip_valuations
194973,0xbcf02e2b7cb43fce05a8a3b8dd3010f87f5397395db7...,21458,0x538cadb95f3c382f3b6ad099c14f91c49aad90e20bce...,13361254,0,0x56f03dbc2d16f4a252a7176e1fc3f05b53c6aad5,0xa57bd00134b2850b2a1c55860c9e9ea100fdd6cf,0,1200000,92954071090,0x1cff79cd000000000000000000000000aa2ec16d77cf...,1633466693,1.930858e+11,0.000000e+00,2,1.000000e+09,1.000000e+09,1.000000e+00,1.000000e-09
194974,0xce50ae32512398b5fc22e983179ab96cd68ba457a6df...,726,0x538cadb95f3c382f3b6ad099c14f91c49aad90e20bce...,13361254,1,0x5ea20f5865a1334cceea6d1bc674a7699c7752e7,0x000000000755567f4924bf483bdf5a53ebc8ef64,0,220323,138215999253,0x000000a0cbe06695ad61b0a150d79219dcf64e1e6cc0...,1633466693,1.382160e+11,1.382160e+11,2,1.000000e+09,1.000000e+09,1.382160e+11,1.382160e+02
194975,0x5190d7201ed8437220f3bcfa3ff4ee1b79a5374abaf5...,11127,0x538cadb95f3c382f3b6ad099c14f91c49aad90e20bce...,13361254,2,0xb58555fcba6479fced7de1485eb054943a09af7b,0x00000000003b3cc22af3ae1eac0440bcee416b40,0,2000000,92954071090,0x0300cbe0667685cd3ddd862b8745b1082a6acb19e14e...,1633466693,9.295407e+10,0.000000e+00,2,1.000000e+09,1.000000e+09,1.000000e+00,1.000000e-09
194976,0xa80d2669e4bbbc2604f0251a70362bda450534be1fe2...,553,0x538cadb95f3c382f3b6ad099c14f91c49aad90e20bce...,13361254,3,0x8552aa9db5bcaa56d41411a4800309d7d0d35e36,0xdef1c0ded9bec7f1a1670819833240f027b25eff,0,266000,155000000000,0x0f3b31b2000000000000000000000000000000000000...,1633466693,1.550000e+11,1.550000e+11,2,1.000000e+09,1.000000e+09,1.550000e+11,1.550000e+02
194977,0x8fa96b9ce51a2c0248c2491e98290a8611d92299a328...,11128,0x538cadb95f3c382f3b6ad099c14f91c49aad90e20bce...,13361254,4,0xb58555fcba6479fced7de1485eb054943a09af7b,0x00000000003b3cc22af3ae1eac0440bcee416b40,0,2000000,242480518145,0x0400cbe066ba5bde662c17e2adff1075610382b9b691...,1633466693,2.424805e+11,2.424805e+11,2,1.000000e+09,1.000000e+09,2.424805e+11,2.424805e+02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
965764,0x0762560fa72fdb7b92a905b260581b017a8c9ce22d11...,113,0xa8146ae6525c1090e1d15931cc5dcb461d1e8b8c0d27...,13364999,262,0x41c8730c4a8a07d523e25f80c9b477337e16fa9c,0xa4dc59bae0ca1a0e52dac1885199a2fb53b3abe3,0,45000,100976098829,0x3e12170f000000000000000000000000d8aa5ed74e5a...,1633518046,1.089530e+11,1.410000e+09,2,1.000000e+09,1.000000e+09,1.410000e+09,1.410000e+00
965766,0x027bab6777af58610e94f4a5d8bafae9d923646bda11...,425,0xa8146ae6525c1090e1d15931cc5dcb461d1e8b8c0d27...,13364999,264,0x26b3eea1cd34a4aff7ce828a5f71daac042d38e0,0x6ad567e7d23787cbc025f168a102fb394e5a85b0,271499366019297752,21000,100712231644,0x,1633518046,1.915743e+11,1.146133e+09,2,1.000000e+09,1.000000e+09,1.146133e+09,1.146133e+00
965769,0xfb608435b14860a8a7cc52f648d58bd32d58515f376b...,484,0xa8146ae6525c1090e1d15931cc5dcb461d1e8b8c0d27...,13364999,267,0x88004a0f6e7dfc2ef21c49b614eb0a3569e29525,0x9757f2d2b135150bbeb65308d4a91804107cd8d6,287000000000000000,327208,100654122220,0xe99a3f80000000000000000000000000000000000000...,1633518046,1.006541e+11,1.006541e+11,2,1.000000e+09,1.000000e+09,1.006541e+11,1.006541e+02
965770,0xa6e0986b89ca14e87572ca5ae467473221e2ed4a04d2...,312,0xa8146ae6525c1090e1d15931cc5dcb461d1e8b8c0d27...,13364999,268,0x88aa631b427cf96d12d91885e7026a3636d90070,0x9757f2d2b135150bbeb65308d4a91804107cd8d6,789250000000000000,327208,100654122220,0xe99a3f80000000000000000000000000000000000000...,1633518046,1.006541e+11,1.006541e+11,2,1.000000e+09,1.000000e+09,1.006541e+11,1.006541e+02
965771,0x8842a2c108d0ea89794ce24bdbe92022c03a76162331...,1091,0xa8146ae6525c1090e1d15931cc5dcb461d1e8b8c0d27...,13364999,269,0x9af999595a08210fcaa705f0491a800551f73388,0x3d9819210a31b4961b30ef54be2aed79b9c9cd3b,0,351217,100566098829,0x1c3db2e00000000000000000000000009af999595a08...,1633518046,2.010862e+11,1.000000e+09,2,1.000000e+09,1.000000e+09,1.000000e+09,1.000000e+00

In [7]:

al_df=pd.DataFrame({'blocks':usable_blocks,'geth_reccomendation':geth_reccomendation})

#len(my_final_blocks)
post_eip_oct_blx=post_eip_oct_blx.rename(columns={'number':'blocks'})



al_df_post_eip_oct=al_df.set_index('blocks').join(post_eip_oct_blx.set_index('blocks'))

al_df_post_eip_oct['max_fee_reccomendation']=al_df_post_eip_oct['geth_reccomendation']\
+(2*al_df_post_eip_oct['base_fee_per_gas'])

al_df_post_eip_oct=al_df_post_eip_oct.rename(columns={'geth_reccomendation':\
                                  'tip_reccomendation'})

al_df_post_eip_oct=al_df_post_eip_oct.reset_index()
display(al_df_post_eip_oct)



al_df_post_eip_oct.to_csv('al_df_post_eip_oct.csv')

,blocks,tip_reccomendation,gas_limit,gas_used,timestamp,transaction_count,base_fee_per_gas,avg_gas_price,max_fee_reccomendation
0,13361254,1.000000e+09,30000000.0,29991060.0,1.633467e+09,329.0,9.295407e+10,9.820180e+10,1.869081e+11
1,13361255,1.000000e+09,30029295.0,30009091.0,1.633467e+09,339.0,1.045664e+11,1.088645e+11,2.101328e+11
2,13361256,1.000000e+09,30000000.0,28215776.0,1.633467e+09,258.0,1.176196e+11,1.192713e+11,2.362392e+11
3,13361257,1.000000e+09,30000000.0,17087672.0,1.633467e+09,253.0,1.305732e+11,1.365704e+11,2.621465e+11
4,13361258,1.000000e+09,30000000.0,9147269.0,1.633467e+09,135.0,1.328449e+11,1.453968e+11,2.666897e+11
...,...,...,...,...,...,...,...,...,...
4805,13361147,1.000000e+09,30000000.0,22848959.0,1.633465e+09,286.0,1.878652e+11,1.916401e+11,3.767303e+11
4806,13361148,1.000000e+09,30029295.0,1056987.0,1.633465e+09,11.0,2.001531e+11,2.017781e+11,4.013061e+11
4807,13361149,1.000000e+09,30058619.0,21172283.0,1.633465e+09,305.0,1.768952e+11,1.830039e+11,3.547904e+11
4808,13361150,1.000000e+09,30087972.0,5058449.0,1.633465e+09,83.0,1.859331e+11,1.906965e+11,3.728661e+11
4809,13361151,1.000000e+09,30058591.0,14749485.0,1.633465e+09,180.0,1.705063e+11,1.750678e+11,3.420126e+11